(* Jsx Grammar in BNF - By Saber2pr *)

JSX ::= ("(")? JSXOPENED | JSXSELFCLOSE (")")?

PARAMETER ::= "(" (IDENTITY ("," IDENTITY)* (",")?)? ")"

EXPRESSION ::= JSX 
             | STRING 
             | NUMBER 
             | OBJ 
             | ARRAY 
             | ARROWFUNCTION 
             | CALLCHAIN 
             | FUNCTION
             | BLOCK

STATEMENT ::= DECLAREVARIABLE 
            | VARIABLEASSIGN
            | CALLCHAIN
            | IFSTATEMENT

NUMBER ::= digit

TEXT ::= (letter | digit)*

STRING ::= '"' TEXT '"'
         | "'" TEXT "'"

KEYWORD ::= "var"
          | "let"
          | "const"

IDENTITY ::= letter (NUMBER TEXT)?

OBJ ::= "{" (IDENTITY ":" EXPRESSION ("," IDENTITY ":" EXPRESSION)* (",")?)? "}"

ARRAY ::= "[" (EXPRESSION ("," EXPRESSION)* (",")?)? "]"

PROP ::= IDENTITY
       | IDENTITY "=" JSXINNEREXPR
       | IDENTITY "=" STRING

OPENTAG ::= "<" IDENTITY ((PROP)*)? ">"

CLOSETAG ::= "<" "/" IDENTITY ">"

JSXSELFCLOSE ::= "<" IDENTITY ((PROP)*)? "/" ">"

JSXINNEREXPR ::= "{" EXPRESSION "}"

JSXOPENED ::= OPENTAG (((JSX | TEXT)*)|JSXINNEREXPR) CLOSETAG

ARROWFUNCTION ::= PARAMETER "=" ">" EXPRESSION

FUNCTION ::= "function" (IDENTITY)? PARAMETER BLOCK

CALLCHAIN ::= (STRING|OBJ|ARRAY|IDENTITY) ("." IDENTITY (PARAMETER)?)*
            | IDENTITY PARAMETER

VARIABLEASSIGN ::= IDENTITY "=" EXPRESSION

BLOCK ::= "{" STATEMENT (";" STATEMENT)* (";")? "}"

DECLAREVARIABLE ::= KEYWORD IDENTITY
                  | KEYWORD VARIABLEASSIGN

IFSTATEMENT ::= "if" PARAMETER (BLOCK|STATEMENT) ("else" (BLOCK|STATEMENT))?

RETURNSTATEMENT ::= "return" EXPRESSION

PROGRAM ::= (STATEMENT)*