name: Jest Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

jobs:
  Jest-Tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deps
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          verbose: true
