name: Npm Publish
on:
  workflow_dispatch:
#   push:
#     tags:
#       - 'v*.*.*'

jobs:
  Npm-Publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Deps
        run: yarn install

      - name: publish with latest tag
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}